const cfg=window.SIDE_CONFIG||{};
const hasConfig=cfg.SUPABASE_URL&&cfg.SUPABASE_PUBLISHABLE_KEY&&!cfg.SUPABASE_URL.includes('TU-PROYECTO');
const supabaseClient=hasConfig&&window.supabase?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY):null;
const $=id=>document.getElementById(id);
const state={modes:{cycles:'manual'},reports:[],events:[],round:1,timer:null,seconds:600,roundClosed:false};
const POSSIBLE_EVENTS=[
 {text:'El precio del cuero sube temporalmente.',type:'mercado'},
 {text:'Cambio de moda: aumenta la demanda de una línea.',type:'demanda'},
 {text:'Contracción del mercado: baja la demanda.',type:'demanda'},
 {text:'Boom de mercado: aumenta la demanda.',type:'demanda'},
 {text:'Nueva norma ambiental incrementa costos operativos.',type:'regulación'},
 {text:'Arancel o impuesto extraordinario afecta insumos.',type:'regulación'},
 {text:'Problema de abastecimiento afecta disponibilidad de materiales.',type:'abastecimiento'}
];
const DEMO_REPORTS=[
 {id:'demo-1',nombre:'Jugador 1',empresa:'BOSS BAGS · Equipo 1',partida:'SIDE-000',ronda:1,capital:100000,ingresos:12000,costos:18600,utilidad:-6600,rondasActivas:1,actividad:7,decisiones:['Estándar','Mesa de corte','Página web'],score:62,estado:'activa',tomandoDecisiones:true,caja:81400},
 {id:'demo-2',nombre:'Jugador 2',empresa:'BOSS BAGS · Equipo 2',partida:'SIDE-000',ronda:1,capital:100000,ingresos:14500,costos:22100,utilidad:-7600,rondasActivas:1,actividad:9,decisiones:['Premium','Máquina semi-industrial','Miraflores'],score:68,estado:'activa',tomandoDecisiones:false,caja:77900}
];
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2600)}
function money(n){return 'S/ '+Number(n||0).toLocaleString('es-PE',{maximumFractionDigits:0})}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function escapeAttr(v){return escapeHtml(v)}
function randomInt(a,b){a=Math.ceil(Number(a));b=Math.floor(Number(b));if(b<a)[a,b]=[b,a];return Math.floor(Math.random()*(b-a+1))+a}
function setDefaultDates(){const now=new Date(),end=new Date(now);end.setMonth(end.getMonth()+2);$('startDate').value=now.toISOString().slice(0,10);$('endDate').value=end.toISOString().slice(0,10)}
function roundSeconds(){return Math.max(0,Number($('roundHours').value||0)*3600+Number($('roundMinutes').value||0)*60+Number($('roundSecs').value||0))}
function getConfig(){return {nombre:$('gameName').value,curso:$('gameCourse').value,codigo:$('gameCode').value,fixedCompany:$('fixedCompany').value,capital:Number($('capital').value||100000),demandLosOlivos:Number($('demandLosOlivos').value||0),demandMiraflores:Number($('demandMiraflores').value||0),demandSJL:Number($('demandSJL').value||0),interest:Number($('interest').value||20),loanMax:Number($('loanMax').value||0),creditPercentStart:Number($('creditPercentStart').value||20),cycles:Number($('cycles').value||6),cyclesMin:Number($('cyclesMin').value||4),cyclesMax:Number($('cyclesMax').value||8),roundHours:Number($('roundHours').value||0),roundMinutes:Number($('roundMinutes').value||10),roundSecs:Number($('roundSecs').value||0),round:Number($('currentRound').value||1),cycleCloseMode:$('cycleCloseMode').value,startDate:$('startDate').value,endDate:$('endDate').value,modes:{...state.modes}}}
function saveConfig(silent=false){localStorage.setItem('SIDE_TEACHER_CONFIG',JSON.stringify(getConfig()));localStorage.setItem('SIDE_TEACHER_MODES',JSON.stringify(state.modes));$('gameCodeBadge').textContent=$('gameCode').value||'SIDE-000';if(!silent)toast('Configuración guardada.')}
function startGame(){saveConfig(true);state.round=1;$('currentRound').value=1;localStorage.setItem('SIDE_ACTIVE_ROUND','1');localStorage.setItem('SIDE_GAME_STATUS',JSON.stringify({active:true,startedAt:new Date().toISOString(),code:$('gameCode').value}));state.seconds=roundSeconds();state.roundClosed=false;updateTimer();updateRoundDisplay();toast('Partida iniciada. El ciclo 1 está activo.');switchTab('rondas')}
function loadConfig(){const raw=localStorage.getItem('SIDE_TEACHER_CONFIG');if(raw){try{const c=JSON.parse(raw);Object.keys(c).forEach(k=>{if(k==='modes')return;if($(k))$(k).value=c[k]??$(k).value});Object.assign(state.modes,c.modes||{})}catch{}}else setDefaultDates();if(!$('startDate').value||!$('endDate').value)setDefaultDates();try{Object.assign(state.modes,JSON.parse(localStorage.getItem('SIDE_TEACHER_MODES')||'{}'))}catch{};state.round=Number(localStorage.getItem('SIDE_ACTIVE_ROUND')||$('currentRound').value||1);$('currentRound').value=state.round;state.seconds=roundSeconds()}
function setMode(key,mode){state.modes[key]=mode;document.querySelectorAll(`[data-mode-for="${key}"] button`).forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));if(key==='cycles'&&mode==='random'){$('cycles').value=randomInt($('cyclesMin').value,$('cyclesMax').value);toast('Número de ciclos generado aleatoriamente.')}saveConfig(true);updateRoundDisplay()}
function restoreModes(){Object.keys(state.modes).forEach(k=>setMode(k,state.modes[k]))}
function addEvent(text,type='sistema'){state.events.unshift({round:state.round,text,type,at:new Date().toLocaleTimeString('es-PE',{hour:'2-digit',minute:'2-digit'})});localStorage.setItem('SIDE_EVENT_LOG',JSON.stringify(state.events));renderEvents()}
function renderEvents(){$('eventLog').innerHTML=state.events.map(e=>`<div class="event-entry"><span>Ciclo ${e.round}: ${escapeHtml(e.text)}</span><small>${e.at}</small></div>`).join('')||'<p class="hint">No hay eventos registrados.</p>'}
function maybeTriggerEvent(){if(Math.random()<0.42){addEvent('No ocurrió ningún evento extraordinario en este ciclo.','sin-evento');return 'Sin evento extraordinario'}const ev=POSSIBLE_EVENTS[randomInt(0,POSSIBLE_EVENTS.length-1)];addEvent(ev.text,ev.type);return ev.text}
function updateRoundDisplay(){$('roundDisplay').textContent=`${state.round} / ${Number($('cycles').value||6)}`;$('currentRound').value=state.round;localStorage.setItem('SIDE_ACTIVE_ROUND',String(state.round));$('roundSummary').textContent=`TEA actual: ${Number($('interest').value||0).toFixed(1)}% · Cierre ${$('cycleCloseMode').value==='automatic'?'automático':'manual'}`}
function updateTimer(){const s=Math.max(0,state.seconds),h=String(Math.floor(s/3600)).padStart(2,'0'),m=String(Math.floor((s%3600)/60)).padStart(2,'0'),sec=String(s%60).padStart(2,'0');$('roundTimer').textContent=`${h}:${m}:${sec}`}
function stopTimer(){if(state.timer){clearInterval(state.timer);state.timer=null}$('startTimer').textContent='Iniciar'}
function finishTime(){stopTimer();state.roundClosed=true;$('roundState').textContent='Tiempo finalizado';addEvent('Tiempo del ciclo agotado.','sistema');if($('cycleCloseMode').value==='automatic')advanceRound(true);else toast('Tiempo agotado. El profesor puede cerrar o avanzar el ciclo.')}
function startTimer(){if(state.timer){stopTimer();$('roundState').textContent='Pausado';return}if(state.roundClosed){toast('Este ciclo ya está cerrado. Avanza al siguiente.');return}if(state.seconds<=0)state.seconds=roundSeconds();$('roundState').textContent='Ciclo en curso';$('startTimer').textContent='Pausar';state.timer=setInterval(()=>{state.seconds--;updateTimer();if(state.seconds<=0)finishTime()},1000)}
function cutRound(){if($('cycleCloseMode').value!=='manual'){toast('El corte anticipado está disponible cuando el cierre es manual.');return}stopTimer();state.seconds=0;updateTimer();state.roundClosed=true;$('roundState').textContent='Ciclo cortado por docente';addEvent('El docente cortó el tiempo antes de finalizar.','sistema');toast('Tiempo cortado. Puedes pasar al siguiente ciclo.')}
function advanceRound(fromAuto=false){const max=Number($('cycles').value||6);if(state.round>=max){stopTimer();state.roundClosed=true;$('roundState').textContent='Simulación finalizada';toast('La simulación llegó al último ciclo.');return}const eventText=maybeTriggerEvent();state.round++;state.roundClosed=false;state.seconds=roundSeconds();const oldRate=Number($('interest').value||20),newRate=Math.max(0,Math.round((oldRate-1)*10)/10);$('interest').value=newRate;saveConfig(true);updateTimer();updateRoundDisplay();$('roundState').textContent=fromAuto?'Nuevo ciclo iniciado automáticamente':'Nuevo ciclo listo';$('roundSummary').textContent=`${eventText} · TEA del nuevo ciclo: ${newRate.toFixed(1)}%`;loadReports();if(fromAuto)startTimer();else toast(`Ciclo ${state.round} disponible.`)}
function loadReports(){try{const saved=JSON.parse(localStorage.getItem('SIDE_STUDENT_REPORTS')||'[]');state.reports=saved.length?saved:DEMO_REPORTS.map(x=>({...x}))}catch{state.reports=DEMO_REPORTS.map(x=>({...x}))}state.reports=state.reports.filter(r=>r.partida===$('gameCode').value||!r.partida);if(!state.reports.length)state.reports=DEMO_REPORTS.map(x=>({...x}));renderCompanies();renderResults();renderWinnerSelect()}
function renderCompanies(){const grid=$('companiesGrid');grid.innerHTML=state.reports.map((r,i)=>`<article class="company-card"><div class="company-status-line"><span class="live-dot ${r.tomandoDecisiones?'online':'idle'}"></span><b>${r.tomandoDecisiones?'ACTIVO · TOMANDO DECISIONES':'SIN ACTIVIDAD RECIENTE'}</b></div><h3>${escapeHtml(r.empresa)}</h3><small>${escapeHtml(r.nombre||'Jugador')} · ciclo ${r.rondasActivas||r.ronda||0}</small><div class="score">${Number(r.score||0)} pts</div><div class="metric"><span>Caja</span><b>${money(r.caja??r.capital)}</b></div><div class="metric"><span>Utilidad</span><b class="${r.utilidad>=0?'profit':'loss'}">${money(r.utilidad)}</b></div><div class="metric"><span>Estado</span><b>${r.estado||'activa'}</b></div><button class="eliminate" data-eliminate="${i}">${r.estado==='eliminada'?'Reactivar empresa':'Eliminar por inactividad'}</button></article>`).join('')||'<div class="card">No hay empresas reportadas.</div>';grid.querySelectorAll('[data-eliminate]').forEach(b=>b.addEventListener('click',()=>toggleElimination(Number(b.dataset.eliminate))))}
function toggleElimination(i){const r=state.reports[i];if(!r)return;r.estado=r.estado==='eliminada'?'activa':'eliminada';persistReports();renderCompanies();renderResults();renderWinnerSelect();toast(r.empresa+(r.estado==='eliminada'?' fue marcada como eliminada.':' fue reactivada.'))}
function persistReports(){localStorage.setItem('SIDE_STUDENT_REPORTS',JSON.stringify(state.reports))}
function renderResults(){const active=state.reports.filter(r=>r.estado!=='eliminada'),totalProfit=active.reduce((s,r)=>s+Number(r.utilidad||0),0),best=active.slice().sort((a,b)=>Number(b.score||0)-Number(a.score||0))[0];$('resultStats').innerHTML=[['Empresas',state.reports.length],['Activas',active.length],['Utilidad total',money(totalProfit)],['Mayor puntaje',best?`${best.score} pts`:'—']].map(x=>`<div class="stat"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('');$('resultsBody').innerHTML=state.reports.map(r=>`<tr><td><b>${escapeHtml(r.empresa)}</b><br><small>${escapeHtml(r.nombre||'')}</small></td><td>${money(r.capital)}</td><td>${money(r.ingresos)}</td><td>${money(r.costos)}</td><td class="${r.utilidad>=0?'profit':'loss'}">${money(r.utilidad)}</td><td>${r.rondasActivas||r.ronda||0}</td><td>${r.actividad||0}</td><td>${r.estado}</td></tr>`).join('');$('detailReports').innerHTML=state.reports.map(r=>`<div class="report-detail"><h4>${escapeHtml(r.empresa)} · ${r.score||0} pts</h4><p><b>Actividad:</b> ${r.tomandoDecisiones?'Tomando decisiones ahora':'Sin actividad reciente'}<br><b>Decisiones:</b> ${(r.decisiones||[]).map(escapeHtml).join(' · ')||'Sin detalle recibido'}<br><b>Actualizado:</b> ${r.updatedAt?new Date(r.updatedAt).toLocaleString('es-PE'):'simulación'}</p></div>`).join('')}
function renderWinnerSelect(){const sel=$('winnerSelect'),active=state.reports.filter(r=>r.estado!=='eliminada');sel.innerHTML=active.map(r=>`<option value="${escapeAttr(r.empresa)}">${escapeHtml(r.empresa)} — ${r.score||0} pts</option>`).join('');renderPodium()}
function renderPodium(){const winner=$('winnerSelect').value;let list=state.reports.filter(r=>r.estado!=='eliminada').sort((a,b)=>Number(b.score||0)-Number(a.score||0));if(winner){const idx=list.findIndex(r=>r.empresa===winner);if(idx>0)[list[0],list[idx]]=[list[idx],list[0]]}const names=['🥇','🥈','🥉'],classes=['first','second','third'];$('podiumPreview').innerHTML=list.slice(0,3).map((r,i)=>`<div class="podium-place ${classes[i]}"><span>${names[i]}</span><strong>${escapeHtml(r.empresa)}</strong><small>${r.score||0} pts</small></div>`).join('')||'<p>Sin empresas activas.</p>'}
function publishPodium(){const winner=$('winnerSelect').value;if(!winner){toast('Selecciona una empresa ganadora.');return}const list=state.reports.filter(r=>r.estado!=='eliminada').sort((a,b)=>Number(b.score||0)-Number(a.score||0)),idx=list.findIndex(r=>r.empresa===winner);if(idx>0)[list[0],list[idx]]=[list[idx],list[0]];const publication={publishedAt:new Date().toISOString(),winner,reason:$('winnerReason').value,podium:list.slice(0,3).map(r=>({empresa:r.empresa,score:r.score}))};localStorage.setItem('SIDE_PUBLISHED_PODIUM',JSON.stringify(publication));$('podiumState').textContent='Publicado';$('publishStatus').textContent='Podio publicado: '+new Date(publication.publishedAt).toLocaleString('es-PE');renderPodium();toast('Podio publicado correctamente.')}
function loadPublished(){try{const p=JSON.parse(localStorage.getItem('SIDE_PUBLISHED_PODIUM')||'null');if(p){$('winnerSelect').value=p.winner;$('winnerReason').value=p.reason||'';$('podiumState').textContent='Publicado';$('publishStatus').textContent='Publicado: '+new Date(p.publishedAt).toLocaleString('es-PE');renderPodium()}}catch{}}
function switchTab(tab){document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.id==='tab-'+tab));const titles={configuracion:'Configuración de la simulación',rondas:'Ciclos y eventos',empresas:'Empresas participantes',resultados:'Resultados de estudiantes',podio:'Ganador y podio'};$('pageTitle').textContent=titles[tab];if(['empresas','resultados','podio'].includes(tab))loadReports();if(tab==='podio')loadPublished()}
function makePdf(){const {jsPDF}=window.jspdf,doc=new jsPDF({unit:'pt',format:'a4'}),c=getConfig(),active=state.reports.filter(r=>r.estado!=='eliminada');doc.setFont('helvetica','bold');doc.setFontSize(19);doc.text('SIDE — Reporte de simulación',40,45);doc.setFontSize(10);doc.setFont('helvetica','normal');doc.text(`${c.nombre} · ${c.curso} · ${c.codigo}`,40,63);let y=92;doc.setFont('helvetica','bold');doc.text('Configuración',40,y);y+=18;doc.setFont('helvetica','normal');[`Caja inicial: ${money(c.capital)}`,`Demanda Los Olivos: ${c.demandLosOlivos}`,`Demanda Miraflores: ${c.demandMiraflores}`,`Demanda SJL: ${c.demandSJL}`,`TEA actual: ${c.interest}%`,`Préstamo máximo: ${money(c.loanMax)}`,`Ciclos: ${c.cycles}`,`Duración: ${c.roundHours} h ${c.roundMinutes} min ${c.roundSecs||0} seg`,`Cierre: ${c.cycleCloseMode}`].forEach(t=>{doc.text(t,40,y);y+=14});y+=12;doc.setFont('helvetica','bold');doc.text('Resultados',40,y);y+=18;active.forEach((r,i)=>{if(y>750){doc.addPage();y=45}doc.setFont('helvetica','bold');doc.text(`${i+1}. ${r.empresa} — ${r.score||0} pts`,40,y);y+=14;doc.setFont('helvetica','normal');doc.text(`Caja: ${money(r.caja??r.capital)} | Ingresos: ${money(r.ingresos)} | Costos: ${money(r.costos)} | Utilidad: ${money(r.utilidad)}`,50,y);y+=16});return doc}
function showPdf(){const doc=makePdf(),blob=doc.output('blob'),url=URL.createObjectURL(blob);$('pdfFrame').src=url;$('pdfModal').classList.remove('hidden')}
function downloadPdf(){makePdf().save(($('gameCode').value||'SIDE-000')+'-reporte.pdf')}

document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));
document.querySelectorAll('.segmented button').forEach(b=>b.addEventListener('click',()=>setMode(b.parentElement.dataset.modeFor,b.dataset.mode)));
$('saveAll').addEventListener('click',()=>saveConfig(false));$('startGame').addEventListener('click',startGame);$('refreshReports').addEventListener('click',()=>{loadReports();toast('Información actualizada.')});$('advanceRound').addEventListener('click',()=>advanceRound(false));$('startTimer').addEventListener('click',startTimer);$('cutRound').addEventListener('click',cutRound);$('clearEvents').addEventListener('click',()=>{state.events=[];localStorage.removeItem('SIDE_EVENT_LOG');renderEvents()});$('publishPodium').addEventListener('click',publishPodium);$('winnerSelect').addEventListener('change',renderPodium);$('viewPdf').addEventListener('click',showPdf);$('downloadPdf').addEventListener('click',downloadPdf);$('closePdf').addEventListener('click',()=>$('pdfModal').classList.add('hidden'));$('backHome').addEventListener('click',()=>window.location.href='index.html');

(async function init(){loadConfig();restoreModes();try{state.events=JSON.parse(localStorage.getItem('SIDE_EVENT_LOG')||'[]')}catch{}updateTimer();updateRoundDisplay();loadReports();renderEvents();loadPublished();if(supabaseClient){const {data:{session}}=await supabaseClient.auth.getSession();$('connectionDot').style.background=session?'#46d59a':'#f3c95f';$('connectionText').textContent=session?'Supabase conectado':'Modo simulación / sin sesión'}})();
