/* Read-only student statements. All amounts come from SIDE_FINANCIAL_MODEL. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.SIDE_STUDENT_FINANCIAL_VIEW=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const amount=value=>`S/ ${Number(value||0).toLocaleString('es-PE',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
  const groups=[
    ['Estado de resultados','estadoResultados',[['Ingresos','ingresos'],['Devoluciones','devoluciones'],['Ventas netas','ventasNetas'],['Costos','costos'],['Impacto de eventos','impactoEventos'],['Otros movimientos','otros'],['Resultado por venta de activos','resultadoVentaActivos'],['Utilidad','utilidad']]],
    ['Balance de caja','balanceCaja',[['Caja inicial','cajaInicial'],['Entradas','entradas'],['Salidas','salidas'],['Préstamos recibidos','prestamos'],['Caja final','cajaFinal']]],
    ['Flujo de caja','flujoCaja',[['Cobros por ventas','cobrosVentas'],['Reembolsos','reembolsos'],['Pagos de operación','pagosOperacion'],['Eventos','eventos'],['Otros movimientos','otros'],['Flujo de operación','operacion'],['Compra de activos','compraActivos'],['Venta de activos','ventaActivos'],['Flujo de inversión','inversion'],['Financiamiento','financiamiento'],['Flujo neto','flujoNeto'],['Caja inicial','cajaInicial'],['Caja final','cajaFinal']]],
    ['Balance general','balanceGeneral',[['Efectivo','efectivo'],['Activos fijos','activosFijos'],['Activos totales','activos'],['Deuda / préstamos','deuda'],['Capital aportado','capital'],['Resultados acumulados','resultadosAcumulados'],['Patrimonio','patrimonio'],['Pasivo + patrimonio','pasivoPatrimonio']]]
  ];
  function cycleRows(report){return Array.isArray(report?.history)?report.history.filter(row=>Number.isInteger(row.round)&&row.round>=1):[];}
  function statementHtml(row){return groups.map(([title,key,fields])=>`<div class="student-statement"><h4>${title}</h4>${fields.map(([label,field])=>`<div><span>${label}</span><strong>${amount(row[key]?.[field])}</strong></div>`).join('')}</div>`).join('');}
  function trendHtml(rows){return `<div class="student-trend" role="img" aria-label="Tendencia de utilidad y caja por ciclo">${rows.map(row=>`<div><span>Ciclo ${row.round}</span><strong>Utilidad ${amount(row.estadoResultados?.utilidad)}</strong><small>Caja ${amount(row.balanceCaja?.cajaFinal)}</small></div>`).join('')}</div>`;}
  function summaryHtml(report,finished=false){const rows=cycleRows(report);if(!rows.length)return '<p>Aún no hay ciclos para revisar.</p>';const latest=rows.at(-1);return `<section class="student-financial-summary" aria-label="Resumen financiero acumulado"><h3>Resultados de todos los ciclos</h3><p>Hasta el ciclo ${latest.round}${finished?' · simulación finalizada':' · cifras del ciclo actual en curso'}. Los importes proceden de movimientos guardados.</p><div class="student-summary-kpis"><div><span>Caja actual</span><strong>${amount(latest.balanceCaja?.cajaFinal)}</strong></div><div><span>Utilidad acumulada</span><strong>${amount(latest.balanceGeneral?.resultadosAcumulados)}</strong></div><div><span>Deuda / préstamos</span><strong>${amount(latest.balanceGeneral?.deuda)}</strong></div></div>${trendHtml(rows)}${rows.map(row=>`<details class="student-cycle-report" ${row.round===latest.round?'open':''}><summary>Ciclo ${row.round} · utilidad ${amount(row.estadoResultados?.utilidad)} · caja ${amount(row.balanceCaja?.cajaFinal)}</summary><div class="student-statement-grid">${statementHtml(row)}</div></details>`).join('')}</section>`;}
  function officeHtml(report){if(!report)return '';const er=report.estadoResultados||{},bc=report.balanceCaja||{},fc=report.flujoCaja||{},bg=report.balanceGeneral||{};return `<section class="student-office-finance" aria-label="Información financiera de la empresa"><h3>Información financiera · ciclo ${report.round}</h3><div class="student-office-grid">${[['Caja',bc.cajaFinal],['Ingresos',er.ingresos],['Costos',er.costos],['Utilidad',er.utilidad],['Deuda / préstamos',bg.deuda],['Flujo neto',fc.flujoNeto],['Activos',bg.activos],['Patrimonio',bg.patrimonio]].map(([name,value])=>`<div><span>${name}</span><strong>${amount(value)}</strong></div>`).join('')}</div><details><summary>Ver estados financieros e indicadores</summary><div class="student-statement-grid">${statementHtml(report)}</div></details></section>`;}
  return Object.freeze({cycleRows,summaryHtml,officeHtml});
});
