const {PGlite}=require('@electric-sql/pglite');
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..');
const professor='11111111-1111-1111-1111-111111111111';
async function database(){
 const db=new PGlite();
 await db.exec(`
 create role anon; create role authenticated; create schema auth;
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
 create table auth.users(id uuid primary key,raw_user_meta_data jsonb,email text);
 create function gen_random_bytes(n integer) returns bytea language sql as $$select decode(substr(md5(random()::text),1,n*2),'hex')$$;
 create table empresas(id bigint generated by default as identity primary key,nombre_legal text,nombre_comercial text,caja_inicial numeric,caja_actual numeric,ciclo_actual integer default 1,reputacion numeric);
 create table decisiones_catalogo(id serial primary key,categoria text,categoria_nombre text,decision_id text,decision_nombre text,tipo text,es_recurrente boolean,es_obligatoria boolean,costo_base numeric,descripcion text,activo boolean);
 create table decisiones_opciones(id serial primary key,decision_id integer,opcion_id text,etiqueta text,descripcion text,costo numeric,capacidad_diaria numeric,tasa_liquidacion numeric,canal text,distrito text,demanda_factor numeric,compromiso_ciclos integer,activo boolean default true);
 create table empresas_decisiones(id serial primary key,empresa_id bigint,ciclo integer,decision_id integer,opcion_id integer,cantidad integer,costo_total numeric,enviada boolean,updated_at timestamptz default now());
 `);
 // The installed Supabase project already owns these four business tables.
 const base=fs.readFileSync(path.join(root,'docs/supabase_migration.sql'),'utf8').replace(/create extension if not exists "pgcrypto";/,'');
 await db.exec(base);
 const migration=fs.readFileSync(path.join(root,'docs/supabase_game_lifecycle.sql'),'utf8');
 await db.exec(migration);await db.exec(migration); // Repeatable deployment.
 await db.query(`insert into auth.users(id,raw_user_meta_data,email) values($1,'{}','test@example.invalid')`,[professor]);
 await db.query(`select set_config('test.uid',$1,false)`,[professor]);
 return db;
}
const config=(overrides={})=>({lifecycleVersion:2,cycleCloseMode:'manual',integrationDurationMinutes:5,integrationMinutes:0,cycles:3,roundHours:0,roundMinutes:10,enabledEvents:[],...overrides});
async function createGame(db,c=config()){
 return (await db.query(`insert into partidas(profesor_id,nombre,configuracion) values($1,'Prueba',$2) returning *`,[professor,c])).rows[0];
}
async function rpc(db,name,args){
 const entries=Object.entries(args);
 const result=await db.query(`select public.${name}(${entries.map(([key],i)=>`${key} => $${i+1}`).join(',')}) as result`,entries.map(([,v])=>v));
 return result.rows[0].result;
}
module.exports={database,config,createGame,rpc,professor};
